FROM registry.access.redhat.com/jboss-webserver-3/webserver30-tomcat8-openshift

EXPOSE 8080 8888

RUN curl https://github.com/s1lawlor/samplebindep/tree/master/libs/sample.war -o $JBOSS_HOME/standalone/deployments/sample.war